// <auto-generated />
using Entity_Framework_Code_First_LAB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entity_Framework_Code_First_LAB.Migrations
{
    [DbContext(typeof(ForumDbContext))]
    [Migration("20251113093319_User_EmailAdded")]
    partial class User_EmailAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entity_Framework_Code_First_LAB.Data.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PostContent")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PostContent = "Hello, this is my first post in this awesome app!!!",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            PostContent = "Bob is cool",
                            UserId = 4
                        },
                        new
                        {
                            Id = 3,
                            PostContent = "cobom",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Entity_Framework_Code_First_LAB.Data.Entities.PostAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerContent")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("PostAnswers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnswerContent = "bob is not cool",
                            PostId = 2,
                            UserId = 3
                        },
                        new
                        {
                            Id = 2,
                            AnswerContent = "Hahaha you loser _|_",
                            PostId = 1,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Entity_Framework_Code_First_LAB.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Email@gmail.com",
                            Username = "Pesho_13"
                        },
                        new
                        {
                            Id = 2,
                            Email = "gosho@gmail.com",
                            Username = "Gosho_15"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Bob@gmail.com",
                            Username = "Bob_12"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Terminator1999@gmail.com",
                            Username = "Terminator"
                        });
                });

            modelBuilder.Entity("Entity_Framework_Code_First_LAB.Data.Entities.Post", b =>
                {
                    b.HasOne("Entity_Framework_Code_First_LAB.Data.Entities.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entity_Framework_Code_First_LAB.Data.Entities.PostAnswer", b =>
                {
                    b.HasOne("Entity_Framework_Code_First_LAB.Data.Entities.Post", "Post")
                        .WithMany("PostAnswers")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity_Framework_Code_First_LAB.Data.Entities.User", "User")
                        .WithMany("Answers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entity_Framework_Code_First_LAB.Data.Entities.Post", b =>
                {
                    b.Navigation("PostAnswers");
                });

            modelBuilder.Entity("Entity_Framework_Code_First_LAB.Data.Entities.User", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
